version: '3.8'

services:
    eghatha:
        image: eghatha:latest
        build: .
        ports:
            - 8501:8501
        env_file:
            - ".env"
        volumes:
            - ./app:/app